<paste log output from Kubernetes-mediated prediction, here>
error: failed to create deployment: deployments.apps "mlapi" already exists
NAME                     READY   STATUS    RESTARTS   AGE
mlapi-8674984857-t2gcq   1/1     Running   0          9m59s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80

Handling connection for 8000

Handling connection for 8000

^C * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 845-971-279
[2022-08-09 15:32:41,198] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-08-09 15:32:41,215] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 15:32:41,224] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 15:32:41,227] INFO in app: Prediction: 
[20.35373177134412]
127.0.0.1 - - [09/Aug/2022 15:32:41] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [09/Aug/2022 15:37:20] "GET / HTTP/1.1" 200 -